"use client";

import {
	ChartBarIcon,
	ChatCircleIcon,
	SidebarIcon,
	TableIcon,
} from "@phosphor-icons/react";
import { useAtomValue } from "jotai";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { currentArtifactAtom } from "./agent-atoms";

interface AgentCanvasProps {
	onClose: () => void;
}

export function AgentCanvas({ onClose }: AgentCanvasProps) {
	const currentArtifact = useAtomValue(currentArtifactAtom);

	return (
		<div className="flex h-full flex-col">
			<div className="flex shrink-0 items-center justify-between border-b p-4">
				<div className="flex items-center gap-2">
					<div className="flex size-8 items-center justify-center rounded border bg-accent/50">
						{currentArtifact ? (
							<ArtifactIcon type={currentArtifact.type} />
						) : (
							<TableIcon
								className="size-4 text-foreground/60"
								weight="duotone"
							/>
						)}
					</div>
					<div>
						<h3 className="font-medium text-sm">
							{currentArtifact?.title ?? "Canvas"}
						</h3>
						<p className="text-foreground/50 text-xs">
							{currentArtifact
								? getArtifactLabel(currentArtifact.type)
								: "Artifacts & visualizations"}
						</p>
					</div>
				</div>
				<Button onClick={onClose} size="icon" variant="ghost">
					<SidebarIcon className="size-4" />
				</Button>
			</div>

			<ScrollArea className="flex-1">
				{currentArtifact ? (
					<ArtifactContent artifact={currentArtifact} />
				) : (
					<CanvasEmptyState />
				)}
			</ScrollArea>
		</div>
	);
}

function CanvasEmptyState() {
	return (
		<div className="flex h-full min-h-[400px] items-center justify-center p-8">
			<div className="flex flex-col items-center gap-4 text-center">
				<div className="flex size-16 items-center justify-center rounded border border-dashed bg-accent/20">
					<ChatCircleIcon
						className="size-8 text-foreground/20"
						weight="duotone"
					/>
				</div>
				<div className="max-w-xs">
					<p className="mb-1 font-medium text-foreground/60 text-sm">
						No artifacts yet
					</p>
					<p className="text-foreground/40 text-xs">
						Charts, tables, and reports generated by the agent will appear here
					</p>
				</div>
			</div>
		</div>
	);
}

interface ArtifactContentProps {
	artifact: {
		id: string;
		type: "chart" | "table" | "report" | "insight";
		title: string;
		data: unknown;
	};
}

function ArtifactContent({ artifact }: ArtifactContentProps) {
	return (
		<div className="p-4">
			<div className="rounded border border-dashed bg-accent/10 p-8 text-center">
				<ArtifactIcon
					className="mx-auto mb-2 size-8 text-foreground/40"
					type={artifact.type}
				/>
				<p className="text-foreground/70 text-sm">{artifact.title}</p>
				<p className="text-foreground/40 text-xs">
					Artifact rendering coming soon
				</p>
			</div>
		</div>
	);
}

function ArtifactIcon({
	type,
	className,
}: {
	type: string;
	className?: string;
}) {
	const iconClass = className ?? "size-4 text-foreground/60";

	switch (type) {
		case "chart":
			return <ChartBarIcon className={iconClass} weight="duotone" />;
		case "table":
			return <TableIcon className={iconClass} weight="duotone" />;
		default:
			return <TableIcon className={iconClass} weight="duotone" />;
	}
}

function getArtifactLabel(type: string): string {
	switch (type) {
		case "chart":
			return "Chart visualization";
		case "table":
			return "Data table";
		case "report":
			return "Generated report";
		case "insight":
			return "AI insight";
		default:
			return "Artifact";
	}
}
